# Generated by Django 5.2.3 on 2025-06-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artivle',
            new_name='Article',
        ),
    ]
