# Generated by Django 5.2 on 2025-05-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='producta',
            field=models.ManyToManyField(related_name='orders', to='shopapp.product'),
        ),
    ]
